Stomatologia/Stomatologia/Stomatologia/Controllers/AppointmentsController.cs
using Microsoft.AspNet.Identity;
using Stomatologia.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace Stomatologia.Controllers
{
    public class AppointmentsController : Controller
    {
        private StomatologyEntities dbState = new StomatologyEntities();

        private List<DateTime> freeDaysList = new List<DateTime>
        {
            new DateTime(2019,4,22),
            new DateTime(2019,5,1),
            new DateTime(2019,5,2),
            new DateTime(2019,5,3),
            new DateTime(2019,6,20),
            new DateTime(2019,8,15),
            new DateTime(2019,11,1),
            new DateTime(2019,11,11),
            new DateTime(2019,12,24),
            new DateTime(2019,12,25),
            new DateTime(2019,12,26)
        };

        private int patientId;

        [Authorize]
        public ActionResult Archive()
        {
            SetPatientIdIfNeeded();
            var appointments = dbState.Appointments.Where(w => w.PatientId == patientId).Where(w => w.IsAvailable == false).Where(s => s.AppointmentDateTime < DateTime.Now).Include(w => w.Doctors).Include(w => w.Patients);
            appointments = appointments.OrderByDescending(m => m.AppointmentDateTime);
            return View(appointments.ToList());
        }

        // GET: Appointments
        [Authorize]
        public ActionResult Index()
        {
            SetPatientIdIfNeeded();
            var Appointments = dbState.Appointments.Where(w => w.PatientId == patientId).Where(w => w.IsAvailable == false).Where(s => s.AppointmentDateTime >= DateTime.Now).Include(w => w.Doctors).Include(w => w.Patients).OrderBy(o => o.AppointmentDateTime);
            return View(Appointments.ToList());
        }

        // GET: Appointments/Create
        [Authorize]
        public ActionResult Create(int doctorId)
        {
            SetPatientIdIfNeeded();

            DateTime minDate = DateTime.Now.Date.AddDays(1);
            var availableAppointments = dbState.Appointments.Where(s => s.DoctorId == doctorId).Where(s => s.IsAvailable == true).Where(s => s.AppointmentDateTime >= minDate).Select(s => s.AppointmentDateTime);
            var availableAppointmentDates = new List<DateTime>();
            var availableAppointmentDatesAsString = new List<string>();
            foreach (var availableAppointment in availableAppointments)
            {
                if (!availableAppointmentDates.Contains(availableAppointment.Date))
                {
                    availableAppointmentDates.Add(availableAppointment.Date);
                    availableAppointmentDatesAsString.Add(string.Concat(availableAppointment.Month, "/", availableAppointment.Day, "/", availableAppointment.Year));
                }
            }
            NewAppointmentViewModel newViewModel = new NewAppointmentViewModel { DoctorId = doctorId, AvailableDatesString = availableAppointmentDatesAsString, AvailableHoursString = new List<string>() };
            return View(newViewModel);
        }

        // POST: Appointments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "DoctorId,AppointmentDate,AppointmentTime")]NewAppointmentViewModel appointment)
        {
            // take date dirctly from view as string
            string dateFromView = Request.Form["DatePicker"];
            if (appointment.AppointmentDate == null || appointment.AppointmentDate < DateTime.Now)
            {
                // split date to get year, month, day
                string[] dateFromModelSplitted = dateFromView.Split('/');
                int yearFromView = Convert.ToInt32(dateFromModelSplitted[2]);
                int monthFromView = Convert.ToInt32(dateFromModelSplitted[0]);
                int dayFromView = Convert.ToInt32(dateFromModelSplitted[1]);

                // write date in model attribute
                DateTime dateToSet = new DateTime(yearFromView, monthFromView, dayFromView);
                appointment.AppointmentDate = dateToSet;
            }

            int doctorId = appointment.DoctorId;

            // if patient is logged and patientId has not beed saved until now, save it in private field
            SetPatientIdIfNeeded();

            // take hour directly from view as string
            if (appointment.AppointmentTime == null) appointment.AppointmentTime = Request.Form["hoursDropDownList"];

            // split time to hour and minutes
            string[] appointmentInTimeFormat = appointment.AppointmentTime.Split(':');
            double appointmentHour = Convert.ToDouble(appointmentInTimeFormat[0]);
            double appointmentMinutes = Convert.ToDouble(appointmentInTimeFormat[1]);

            // create date to find in database: add time to date created above
            DateTime appointmentToFind = appointment.AppointmentDate.AddHours(appointmentHour).AddMinutes(appointmentMinutes);

            // find the appointment in database
            var appointmentsFound = dbState.Appointments.Where(s => s.DoctorId == appointment.DoctorId).Where(s => s.AppointmentDateTime == appointmentToFind);

            // if no appointment is found, it means that user probably chose something wrong
            if (appointmentsFound.ToList().Count == 0)
            {
                // fill data that should be shown in view if model validation returns errors
                DateTime minDate = DateTime.Now.Date.AddDays(1);
                var availableAppointments = dbState.Appointments.Where(s => s.DoctorId == doctorId).Where(s => s.IsAvailable == true).Where(s => s.AppointmentDateTime >= minDate).Select(s => s.AppointmentDateTime);
                var availableAppointmentDates = new List<DateTime>();
                var availableAppointmentDatesAsString = new List<string>();
                foreach (var availableAppointment in availableAppointments)
                {
                    if (!availableAppointmentDates.Contains(availableAppointment.Date))
                    {
                        availableAppointmentDates.Add(availableAppointment.Date);
                        availableAppointmentDatesAsString.Add(string.Concat(availableAppointment.Month, "/", availableAppointment.Day, "/", availableAppointment.Year));
                    }
                }

                appointment.AvailableDatesString = availableAppointmentDatesAsString;
                appointment.AvailableHoursString = new List<string>();
                ModelState.AddModelError("", "Proszę zweryfikować poprawność wybranego terminu.");
                return View(appointment);
            }

            // if the logged patient has already booked an appointment in the same date and time, prevent it
            var appointmentsWithTheSameDatetime = dbState.Appointments.Where(s => s.AppointmentDateTime == appointmentToFind).Where(s => s.PatientId == patientId);
            if (appointmentsWithTheSameDatetime.Count() > 0)
            {
                // fill data that should be shown in view if model validation returns errors
                DateTime minDate = DateTime.Now.Date.AddDays(1);
                var availableAppointments = dbState.Appointments.Where(s => s.DoctorId == doctorId).Where(s => s.IsAvailable == true).Where(s => s.AppointmentDateTime >= minDate).Select(s => s.AppointmentDateTime);
                var availableAppointmentDates = new List<DateTime>();
                var availableAppointmentDatesAsString = new List<string>();
                foreach (var availableAppointment in availableAppointments)
                {
                    if (!availableAppointmentDates.Contains(availableAppointment.Date))
                    {
                        availableAppointmentDates.Add(availableAppointment.Date);
                        availableAppointmentDatesAsString.Add(string.Concat(availableAppointment.Month, "/", availableAppointment.Day, "/", availableAppointment.Year));
                    }
                }

                appointment.AvailableDatesString = availableAppointmentDatesAsString;
                appointment.AvailableHoursString = new List<string>();
                ModelState.AddModelError("", "W podanym terminie istnieje już zarezerwowana wizyta dla tego użytkownika. Proszę wybrać inny termin.");
                return View(appointment);
            }

            // take "first or default" that is available - we expect exact 1 result in database
            Appointments appointmentToAdd = appointmentsFound.Where(s => s.IsAvailable == true).FirstOrDefault();

            // if no available appointment was found, it means somebody must have just booked this appointment
            if (appointmentToAdd == null)
            {
                // fill data that should be shown in view if model validation returns errors
                DateTime checkDate = DateTime.Now.Date.AddDays(1);
                var availableAppointments = dbState.Appointments.Where(s => s.DoctorId == doctorId).Where(s => s.IsAvailable == true).Where(s => s.AppointmentDateTime >= checkDate).Select(s => s.AppointmentDateTime);
                var availableAppointmentDates = new List<DateTime>();
                var availableAppointmentDatesAsString = new List<string>();
                foreach (var availableAppointment in availableAppointments)
                {
                    if (!availableAppointmentDates.Contains(availableAppointment.Date))
                    {
                        availableAppointmentDates.Add(availableAppointment.Date);
                        availableAppointmentDatesAsString.Add(string.Concat(availableAppointment.Month, "/", availableAppointment.Day, "/", availableAppointment.Year));

Stomatologia/Stomatologia/Stomatologia/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>NOVA - Centrum Stomatologii</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/moment")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/datetime")
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("NOVA - Centrum Stomatologii", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Nasi lekarze", "DoctorsOverview", "Home")</li>
                    <li>@Html.ActionLink("Cennik usług", "Pricing", "Home")</li>
                    <li>@Html.ActionLink("Kontakt", "Contact", "Home")</li>
                    @if (Request.IsAuthenticated)
                    {
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Moje wizyty <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li>@Html.ActionLink("Umów wizytę", "ChooseDoctor", "Appointments")</li>
                                <li>@Html.ActionLink("Nadchodzące wizyty", "Index", "Appointments")</li>
                                <li>@Html.ActionLink("Archiwum wizyt", "Archive", "Appointments")</li>
                            </ul>
                        </li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer class="well well-sm">
            <p>&copy; @DateTime.Now.Year - Michał Kłak, PAZiG - projekt</p>
        </footer>
    </div>

    @RenderSection("scripts", required: false)
</body>
</html>